# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-music"
	LogPath     = "log/gf-music/server"

# Logger.
[logger]
    Path        = "log/gf-music/logger"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:123456@tcp(mysql:3306)/go-music"
    debug = true
    CreatedAt = "CreateTime"
    UpdatedAt = "UpdateTime"
    # Database logger.
    [database.logger]
        Path   = "log/gf-music/sql"
        Level  = "all"
        Stdout = true


#jwt配置
[jwt]
    ExpiresAt = 1 # 3600000000000秒 == 1天 默认设置为1天
    RefreshAt = 168 # 3600000000000秒 == 1天 , 24 * 7 = 168 刷新的token设置为一星期
    SigningKey = "koi29a83idakguqjq29asd9asd8a7jhq"
