[wechat]
    url = "https://xizhi.qqoq.net/XZ6dc3233ddfe6831d3fda139d174a4b97.send"

[qiniu]
    Zone = "ZoneHuabei" # 地区机房
    Bucket = "gf-music"
    ImgPath = "http://store.ssdog.cn"
    UseHTTPS = false # 是否使用https域名
    AccessKey = "dp50sTuARMeOk6FBC9GruqGtdAdO0X3-jMR3wHqj"
    SecretKey = "gx0kITZdk-0tIPTsJyza3Q1iNXiFzJadHrCFR9i8"
    UseCdnDomains = false # 上传是否使用CDN上传加速
    Url = "http://store.ssdog.cn/"